version: '3.8'

services:
  # MET2.4 Development App - Aligned with Production Architecture
  met24-development-app:
    build:
      context: .
      dockerfile: Dockerfile.production  # Use same Dockerfile for consistency
    container_name: met24-development-app
    environment:
      - NODE_ENV=development
      - REACT_APP_NODE_ENV=development
      - REACT_APP_BUILD_TARGET=coolify
      - REACT_APP_API_URL=${REACT_APP_API_URL:-https://dev.your-future-self.app/api}
      - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
      - REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY}
      - REACT_APP_MCP_BRIDGE_URL=${REACT_APP_MCP_BRIDGE_URL:-https://mcp-dev.your-future-self.app}
      - SERVICE_URL_MET24_MCP_BRIDGE=${SERVICE_URL_MET24_MCP_BRIDGE:-https://mcp-dev.your-future-self.app}
      - SERVICE_URL_MET24_USER_APP=${SERVICE_URL_MET24_USER_APP:-https://dev.your-future-self.app}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_EMAIL=${VAPID_EMAIL:-mailto:osteomedica.utrecht@gmail.com}
      - SSL_EMAIL=${SSL_EMAIL:-osteomedica.utrecht@gmail.com}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-app.rule=Host(`dev.your-future-self.app`)"
      - "traefik.http.routers.dev-app.entrypoints=websecure"
      - "traefik.http.routers.dev-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.dev-app.loadbalancer.server.port=80"
      # HTTP to HTTPS redirect
      - "traefik.http.routers.dev-app-http.rule=Host(`dev.your-future-self.app`)"
      - "traefik.http.routers.dev-app-http.entrypoints=web"
      - "traefik.http.routers.dev-app-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  # MCP Bridge - Development (Optional, for testing AI features)
  met24-mcp-bridge-dev:
    build:
      context: .
      dockerfile: Dockerfile.mcp-bridge
    container_name: met24-mcp-bridge-dev
    environment:
      - NODE_ENV=development
      - REACT_APP_NODE_ENV=development
      - REACT_APP_API_URL=${REACT_APP_API_URL:-https://dev.your-future-self.app/api}
      - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
      - REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY}
      - SERVICE_URL_MET24_USER_APP=${SERVICE_URL_MET24_USER_APP:-https://dev.your-future-self.app}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_EMAIL=${VAPID_EMAIL:-mailto:osteomedica.utrecht@gmail.com}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcp-dev.rule=Host(`mcp-dev.your-future-self.app`)"
      - "traefik.http.routers.mcp-dev.entrypoints=websecure"
      - "traefik.http.routers.mcp-dev.tls.certresolver=letsencrypt"
      - "traefik.http.services.mcp-dev.loadbalancer.server.port=3001"
      # HTTP to HTTPS redirect
      - "traefik.http.routers.mcp-dev-http.rule=Host(`mcp-dev.your-future-self.app`)"
      - "traefik.http.routers.mcp-dev-http.entrypoints=web"
      - "traefik.http.routers.mcp-dev-http.middlewares=redirect-to-https"

networks:
  coolify:
    external: true

# Development-specific configuration
# Port mapping: 3002 → dev.your-future-self.app
# Maintains consistency with Production architecture
# Uses same Dockerfiles for build parity
# Enables full AI feature testing with MCP Bridge