/**
 * MET2.4 Domains Schema - WatermelonDB V14
 */

import { tableSchema } from "@nozbe/watermelondb";

export const met24DomainsSchema = [
  tableSchema({
    name: "met24_domains",
    columns: [
      { name: "domain_id", type: "string", isIndexed: true },
      { name: "domain_number", type: "number" },
      { name: "domain_name", type: "string" },
      { name: "domain_description", type: "string", isOptional: true },
      { name: "philosophical_level", type: "string" },
      { name: "practical_applications", type: "string" },
      { name: "theoretical_framework", type: "string", isOptional: true },
      { name: "metadata", type: "string" },
      { name: "last_synced_at", type: "number" },
      { name: "sync_status", type: "string" },
      { name: "created_at", type: "number" },
      { name: "updated_at", type: "number" },
      { name: "created_by", type: "string" },
    ],
  }),
  tableSchema({
    name: "met24_domain_relations",
    columns: [
      { name: "relation_id", type: "string", isIndexed: true },
      { name: "source_domain_id", type: "string", isIndexed: true },
      { name: "target_domain_id", type: "string", isIndexed: true },
      { name: "relation_type", type: "string" },
      { name: "relation_strength", type: "number" },
      { name: "relation_description", type: "string", isOptional: true },
      { name: "bidirectional", type: "boolean" },
      { name: "metadata", type: "string" },
      { name: "last_synced_at", type: "number" },
      { name: "sync_status", type: "string" },
      { name: "created_at", type: "number" },
      { name: "updated_at", type: "number" },
      { name: "created_by", type: "string" },
    ],
  }),
  tableSchema({
    name: "met24_new_insights",
    columns: [
      { name: "insight_id", type: "string", isIndexed: true },
      { name: "domain_id", type: "string", isIndexed: true },
      { name: "insight_title", type: "string" },
      { name: "insight_description", type: "string", isOptional: true },
      { name: "insight_type", type: "string" },
      { name: "evidence_level", type: "number" },
      { name: "source_reference", type: "string", isOptional: true },
      { name: "metadata", type: "string" },
      { name: "last_synced_at", type: "number" },
      { name: "sync_status", type: "string" },
      { name: "created_at", type: "number" },
      { name: "updated_at", type: "number" },
      { name: "created_by", type: "string" },
    ],
  }),
  tableSchema({
    name: "met24_practical_applications",
    columns: [
      { name: "application_id", type: "string", isIndexed: true },
      { name: "domain_id", type: "string", isIndexed: true },
      { name: "application_name", type: "string" },
      { name: "application_description", type: "string", isOptional: true },
      { name: "application_type", type: "string" },
      { name: "difficulty_level", type: "number" },
      { name: "estimated_duration_minutes", type: "number", isOptional: true },
      { name: "materials_needed", type: "string" },
      { name: "metadata", type: "string" },
      { name: "last_synced_at", type: "number" },
      { name: "sync_status", type: "string" },
      { name: "created_at", type: "number" },
      { name: "updated_at", type: "number" },
      { name: "created_by", type: "string" },
    ],
  }),
  tableSchema({
    name: "met24_user_progress",
    columns: [
      { name: "user_id", type: "string", isIndexed: true },
      { name: "domain_id", type: "string", isIndexed: true },
      { name: "progress_percentage", type: "number" },
      { name: "completed_insights", type: "string" },
      { name: "completed_applications", type: "string" },
      { name: "current_insight_id", type: "string", isOptional: true },
      { name: "current_application_id", type: "string", isOptional: true },
      { name: "learning_path", type: "string" },
      { name: "achievements", type: "string" },
      { name: "notes", type: "string", isOptional: true },
      { name: "last_accessed_at", type: "number" },
      { name: "created_at", type: "number" },
      { name: "updated_at", type: "number" },
      { name: "created_by", type: "string" },
    ],
  }),
  tableSchema({
    name: "met24_sync_queue",
    columns: [
      { name: "table_name", type: "string" },
      { name: "record_id", type: "string" },
      { name: "operation", type: "string" },
      { name: "data", type: "string" },
      { name: "status", type: "string" },
      { name: "retry_count", type: "number" },
      { name: "last_attempt_at", type: "number", isOptional: true },
      { name: "error_message", type: "string", isOptional: true },
      { name: "created_at", type: "number" },
      { name: "updated_at", type: "number" },
      { name: "created_by", type: "string" },
    ],
  }),
  tableSchema({
    name: "met24_server_sync_status",
    columns: [
      { name: "user_id", type: "string", isIndexed: true },
      { name: "last_full_sync", type: "number", isOptional: true },
      { name: "last_incremental_sync", type: "number", isOptional: true },
      { name: "sync_frequency", type: "string" },
      { name: "auto_sync_enabled", type: "boolean" },
      { name: "sync_conflicts", type: "string", isOptional: true },
      { name: "server_version", type: "string", isOptional: true },
      { name: "client_version", type: "string" },
      { name: "created_at", type: "number" },
      { name: "updated_at", type: "number" },
      { name: "created_by", type: "string" },
    ],
  }),
];
